# numpy

In [4]:
import numpy as np

In [5]:
np.__version__

'2.1.3'

In [9]:
#create a list
my_list = [0,1,2,3,4,5]
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5]
<class 'list'>


In [10]:
np.array(my_list)

array([0, 1, 2, 3, 4, 5])

In [12]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [14]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
print(np.arange(10,24,3)) # start # end # step
print(np.arange(10,20))
print(np.arange(10))
print(np.arange(10,50,5))

[10 13 16 19 22]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25 30 35 40 45]


In [ ]:
print(np.arange(-20,8))
print(np.arange(20,8)) # this will not work because the first arguent should be less than the second argument

[-20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3
  -2  -1   0   1   2   3   4   5   6   7]
[]


In [33]:
print(np.arange(-20,8,2))

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6]


In [42]:
print(np.zeros(30, dtype=int)) # create an array of zeros with 30 elements
print(np.zeros((3, 4),dtype=int)) # create a 2D array of zeros with 3 rows and 4 columns
print(np.zeros((3, 4),dtype=float)) # create a 2D array of zeros with 3 rows and 4 columns, but with float type
print(np.zeros((3, 4),dtype=bool)) # create a 2D array of zeros with 3 rows and 4 columns, but with boolean type
print(np.zeros((3, 4),dtype=str)) # create a 2D array of zeros with 3 rows and 4 columns, but with string type
print(np.zeros((3, 4),dtype=object) )# create a 2D array of zeros with 3 rows and 4 columns, but with object type
print(np.zeros((3, 4),dtype=complex)) # create a 2D array    of zeros with 3 rows and 4 columns, but with complex type
print(np.zeros((3, 4),dtype=np.int64) )# create a 2D array of zeros with 3 rows and 4 columns, but with int64 type
print(np.zeros((3, 4),dtype=np.float64)) # create a 2D array of zeros with 3 rows and 4 columns, but with float64 type
print(np.zeros((3, 4),dtype=np.complex128)) # create a 2   D array of zeros with 3 rows and 4 columns, but with complex128 type

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[False False False False]
 [False False False False]
 [False False False False]]
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [ ]:
nd = np.zeros((5, 9), dtype=int)
nd.shape # check the shape of the array
nd.ndim # check the number of dimensions of the array

(5, 9)

In [54]:
np.ones(3,dtype=int) # create an array of ones with 3 elements

array([1, 1, 1])

In [52]:
nd1 = np.ones((10,10),dtype=int) # create a 2D array of ones with 10 rows and 10 columns
print(nd1) # print the array
print(nd1.shape) # check the shape of the array
print(nd1.ndim) # check the number of dimensions of the array

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
(10, 10)
2
