# numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
#create a list
my_list = [0,1,2,3,4,5]
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5]
<class 'list'>


In [4]:
np.array(my_list)

array([0, 1, 2, 3, 4, 5])

In [5]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
print(np.arange(10,24,3)) # start # end # step
print(np.arange(10,20))
print(np.arange(10))
print(np.arange(10,50,5))

[10 13 16 19 22]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25 30 35 40 45]


In [8]:
print(np.arange(-20,8))
print(np.arange(20,8)) # this will not work because the first arguent should be less than the second argument

[-20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3
  -2  -1   0   1   2   3   4   5   6   7]
[]


In [9]:
print(np.arange(-20,8,2))

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6]


In [10]:
print(np.zeros(30, dtype=int)) # create an array of zeros with 30 elements
print(np.zeros((3, 4),dtype=int)) # create a 2D array of zeros with 3 rows and 4 columns
print(np.zeros((3, 4),dtype=float)) # create a 2D array of zeros with 3 rows and 4 columns, but with float type
print(np.zeros((3, 4),dtype=bool)) # create a 2D array of zeros with 3 rows and 4 columns, but with boolean type
print(np.zeros((3, 4),dtype=str)) # create a 2D array of zeros with 3 rows and 4 columns, but with string type
print(np.zeros((3, 4),dtype=object) )# create a 2D array of zeros with 3 rows and 4 columns, but with object type
print(np.zeros((3, 4),dtype=complex)) # create a 2D array    of zeros with 3 rows and 4 columns, but with complex type
print(np.zeros((3, 4),dtype=np.int64) )# create a 2D array of zeros with 3 rows and 4 columns, but with int64 type
print(np.zeros((3, 4),dtype=np.float64)) # create a 2D array of zeros with 3 rows and 4 columns, but with float64 type
print(np.zeros((3, 4),dtype=np.complex128)) # create a 2   D array of zeros with 3 rows and 4 columns, but with complex128 type

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[False False False False]
 [False False False False]
 [False False False False]]
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [11]:
nd = np.zeros((5, 9), dtype=int)
nd.shape # check the shape of the array
nd.ndim # check the number of dimensions of the array

2

In [12]:
np.ones(3,dtype=int) # create an array of ones with 3 elements

array([1, 1, 1])

In [13]:
nd1 = np.ones((10,10),dtype=int) # create a 2D array of ones with 10 rows and 10 columns
print(nd1) # print the array
print(nd1.shape) # check the shape of the array
print(nd1.ndim) # check the number of dimensions of the array

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
(10, 10)
2


In [14]:
arr = np.random.randint(0,100,(10,10))
arr

array([[12, 59, 89,  3, 42, 13, 60, 77, 98, 27],
       [61, 31, 33, 25, 87, 33, 57, 21, 84, 40],
       [41, 14, 32, 30, 22, 64, 10, 85, 37, 72],
       [83, 29, 59, 54, 20, 82, 58, 60, 86, 94],
       [35, 73, 45, 74, 51, 93, 16, 16, 80, 58],
       [45, 94, 65,  0, 73, 96, 32, 39,  4,  8],
       [ 3, 43, 83,  8, 24, 82, 78, 51, 21, 30],
       [81, 23, 63, 34, 43, 13, 65, 51, 69, 20],
       [31,  2, 74, 88, 72,  0, 29, 36, 95, 29],
       [55, 90, 99, 64,  2, 88, 47,  0,  6, 67]], dtype=int32)

In [15]:
arr[1,4] # access the element at row 1 and column 4

np.int32(87)

In [16]:
arr[2:5,2:5] # access the elements from row 2 to row 5 and column 2 to column 5

array([[32, 30, 22],
       [59, 54, 20],
       [45, 74, 51]], dtype=int32)

In [17]:
arr[0:10:3] # access every 3rd element from row 0 to row 10

array([[12, 59, 89,  3, 42, 13, 60, 77, 98, 27],
       [83, 29, 59, 54, 20, 82, 58, 60, 86, 94],
       [ 3, 43, 83,  8, 24, 82, 78, 51, 21, 30],
       [55, 90, 99, 64,  2, 88, 47,  0,  6, 67]], dtype=int32)

In [18]:
arr[arr<50]

array([12,  3, 42, 13, 27, 31, 33, 25, 33, 21, 40, 41, 14, 32, 30, 22, 10,
       37, 29, 20, 35, 45, 16, 16, 45,  0, 32, 39,  4,  8,  3, 43,  8, 24,
       21, 30, 23, 34, 43, 13, 20, 31,  2,  0, 29, 36, 29,  2, 47,  0,  6],
      dtype=int32)

In [19]:
arr[arr==50] 

array([], dtype=int32)

In [20]:
# Create an identity matrix
f = np.eye(4)  # 4x4 identity matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array manipulation function

In [21]:
# Reshape an array
a1 = np.array([1, 2, 3,4,5,6])
reshaped = np.reshape(a1, (2, 3))  # Reshape to 2x3
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]
 [4 5 6]]


In [22]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [23]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


# Mathamatical functions

In [24]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [25]:
squared = np.power(g,2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [28]:
a2 = np.array([1, 2, 3,4])
dot_product = np.dot(g,a2)
print("Dot product of g with a2:", dot_product)

Dot product of g with a2: 30


# statistical function

In [33]:
stat_of_value = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17,18,19,20,21])
mean = np.mean(stat_of_value)
print("Mean of stat_of_value:", mean)

Mean of stat_of_value: 11.0


In [34]:
median = np.median(stat_of_value)
print("Median of stat_of_value:", median)

Median of stat_of_value: 11.0


In [35]:
std = np.std(stat_of_value)
print("Standard deviation of stat_of_value:", std)

Standard deviation of stat_of_value: 6.0553007081949835


In [36]:
min = np.min(stat_of_value)
print("Minimum of stat_of_value:", min)

Minimum of stat_of_value: 1


In [37]:
max = np.max(stat_of_value)
print('maimum of stat_of_value:', max)

maimum of stat_of_value: 21


# Linear algebra function

In [39]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print(np.ndim(matrix))  # Check the number of dimensions of the matrix
print("Shape of matrix:", matrix.shape)  # Check the shape of the matrix

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2
Shape of matrix: (3, 3)


# Boolean and logical functions

# for checking all the elements are true we use all() function
# for checking any of the elements are true we use any() function

In [42]:
logical_test = np.array([True,False,True,False])
Check_all = np.all(logical_test)  # Check if all elements are True
Check_any = np.any(logical_test)  # Check if any element is True
print("All elements are True:", Check_all)
print("Any element is True:", Check_any)

All elements are True: False
Any element is True: True


# Set operations

In [45]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a,set_b) # Find the intersection of two sets
print("Intersection of set_a and set_b:", intersection)

Intersection of set_a and set_b: [3 4]


In [ ]:
set1_a = np.array([1, 2, 3, 4])
set1_b = np.array([3, 4, 5, 6])
union = np.union1d(set1_a,set1_b) # Find the union of two sets
print("union of set1_a and set1_b:", union)

union of set1_a and set1_b: [1 2 3 4 5 6]


# array attribute function

In [48]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64
