In [4]:
import random
random.random()

0.8453771169750547

In [38]:
import numpy as np
np.random.rand(3)

array([0.57034559, 0.01200325, 0.91865388])

In [8]:
np.random.rand(2,3)

array([[0.69725206, 0.75796625, 0.6605782 ],
       [0.40420817, 0.69212118, 0.96036617]])

In [23]:
np.random.randint(50)

4

In [ ]:
np.random.randint(2,10) # this will print random values between 2-10 here 2 will be included and 10 will not be included

2

In [34]:
np.random.randint(2,10,4)

array([8, 4, 6, 8], dtype=int32)

In [45]:
matrix =np.random.randint(10,40,(10,10))
matrix
print(matrix.ndim)
print(matrix.shape)

2
(10, 10)


In [46]:
list = [1,2,3,4,5,6,7,8,9]
arr = np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
matrix2 = np.random.randint(10,20,(5,4))
matrix2

array([[17, 19, 17, 14],
       [14, 12, 12, 13],
       [15, 10, 14, 14],
       [18, 13, 15, 18],
       [19, 14, 16, 18]], dtype=int32)

In [55]:
matrix2[1:4]

array([[14, 12, 12, 13],
       [15, 10, 14, 14],
       [18, 13, 15, 18]], dtype=int32)

In [56]:
matrix2[-1:]

array([[19, 14, 16, 18]], dtype=int32)

In [57]:
matrix2[:-1]

array([[17, 19, 17, 14],
       [14, 12, 12, 13],
       [15, 10, 14, 14],
       [18, 13, 15, 18]], dtype=int32)